services:

  mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - ./data:/data/db
      # environment:
      #   MONGO_INITDB_ROOT_USERNAME: root
      #   MONGO_INITDB_ROOT_PASSWORD: example
      # networks:
      #   - app-network
      # healthcheck:
      #   test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      #   interval: 10s
      #   timeout: 5s
      #   retries: 5

networks:
  default:
    name: network