cluster.name: "docker-cluster"
network.host: 0.0.0.0

# Для версий 8.x+ может потребоваться дополнительная настройка безопасности
# xpack.security.enabled: true
# xpack.security.transport.ssl.enabled: true
xpack.security.enabled: false